version: '3.4'

services:
  node:
    image: ${DOCKER_REGISTRY-}CwATE-MA
    build:
      context: .
      dockerfile: CwATE-MA/Dockerfile
    expose:
      - "80"
    environment:
      - ENVIRONMENT=production
      - ASPNETCORE_ENVIRONMENT=Production
      - "CONNECTION_STRING=MSSQL"
    volumes:
      - ./data:/data
      - ./data/favicon.ico:/bin/wwwroot/favicon.ico:ro
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
    ports:
      - "5000:4000"
networks:
  default:
    driver: bridge
    name: czompidev