name: cwatelab
services:
  node:
    image: ${DOCKER_REGISTRY-}cwate-ma
    build:
      context: .
      dockerfile: CwATE-MA/Dockerfile
    expose:
      - "80"
    environment:
      - ENVIRONMENT=production
      - ASPNETCORE_ENVIRONMENT=Production
      - "CONNECTION_STRING=MSSQL"
    #volumes:
      #- ./data:/data
      #- ./data/favicon.ico:/bin/wwwroot/favicon.ico:ro
  proxy:
    image: cr.czompicloud.hu/czsoft/reverse-proxy:latest
    depends_on:
      - node
    ports:
      - "5000:4000"
    restart: unless-stopped
networks:
  default:
    driver: bridge
    name: cwatema_lab